server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sso-realm
keycloak:
  realm: sso-realm
  auth-server-url: http://localhost:8080
  resource: gmail-app # Default client, will validate tokens for all clients
  public-client: true
  bearer-only: true